# Do not modify this file! It was generated by nixos-generate-config.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelParams = [
    "mem_sleep_default=deep"
    "pcie_aspm.policy=powersupersave"
    "acpi.prefer_microsoft_dsm_guid=1"
  ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.blacklistedKernelModules = [ "nouveau" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c565d2e8-e53a-4966-9774-6be88dfb3758";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-31ac403d-4722-4e36-92f4-56d4ce5245b8".device =
    "/dev/disk/by-uuid/31ac403d-4722-4e36-92f4-56d4ce5245b8";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D3B3-DA74";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
