on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

name: Dead Code

permissions:
  contents: read

jobs:
  deadcode:
    name: Dead code analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: deadnix
          skipPush: true
      - name: Run deadnix
        run: nix run nixpkgs#deadnix -- --fail .
